name: storm-tracking-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - uxarray
  - tobac
  - cartopy
  - matplotlib
  - pathlib
  - numpy
  - pandas 
  - xesmf
  - esmpy
  - netcdf4
  - dask 
  
