name: storm-tracking-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - uxarray
  - tobac
  - cartopy
  - matplotlib
  - pathlib
  - numpy
  - pandas
  - dask
  - netcdf4
  - xarray
  - xesmf
  - esmpy=8.4.2
  